1. 使用letcc/throw实现call-with-current-continuation, 基于5_42

直接在5_42里运行
```scheme
   (eopl:pretty-print (run
   " 
   let call-with-current-continuation
   = proc (p)
      letcc cont 
      in (p proc (v) 
              throw v to cont)
   in let f1 = proc (g) 
                 (g 10)
      in (call-with-current-continuation f1)
   "
   ))
```

2. 不实现letcc/throw, 直接实现callcc, 基于ch5/p174_exception

```scheme
x绑定到callcc的cont上, 本质和1的x绑定到proc (v) throw v to cont是一样的, 虽然实现的方式不一样
用2这种方式感觉更好, x直接被绑定在了callcc的continuation上
```